# Generated by Django 5.2.4 on 2025-07-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='description',
        ),
        migrations.AddField(
            model_name='depense',
            name='secteur',
            field=models.CharField(blank=True, choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='date_depense',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='entite',
            field=models.CharField(choices=[('BOUTIQUE', 'Boutique'), ('SALON', 'Salon')], max_length=10),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
