# Generated by Django 5.2.4 on 2025-07-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_depense_description_depense_secteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
