# Generated by Django 5.2.4 on 2025-07-06 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_estimee', models.DurationField(help_text='Format: HH:MM:SS')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_commission', models.DecimalField(decimal_places=2, default=0.3, help_text='Ex: 0.30 pour 30%', max_digits=5)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prestation', models.DateTimeField(auto_now_add=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.personnel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.service')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_calcul', models.DateField(auto_now_add=True)),
                ('est_payee', models.BooleanField(default=False)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.personnel')),
                ('prestation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salon.prestation')),
            ],
        ),
    ]
