# Generated by Django 5.2.4 on 2025-07-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='personnel',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='prenom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
