# Generated by Django 5.2.4 on 2025-07-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_personnel_utilisateur_personnel_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=20, unique=True)),
                ('taux_commission', models.DecimalField(decimal_places=2, help_text='Ex: 0.50 pour 50%', max_digits=5)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='prestation',
            name='secteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='salon.secteur'),
            preserve_default=False,
        ),
    ]
