# Generated by Django 5.2.4 on 2025-07-08 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_secteur_prestation_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='secteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='personnel_affecte', to='salon.secteur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secteur',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secteurs_responsables', to='salon.personnel'),
        ),
    ]
