# Generated by Django 5.2.4 on 2025-07-08 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_personnel_secteur_alter_secteur_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.secteur'),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secteurs_responsables', to=settings.AUTH_USER_MODEL),
        ),
    ]
