# Generated by Django 5.2.4 on 2025-09-05 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_personnel_secteur_alter_secteur_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='date_prestation',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 8, 57, 49, 328444, tzinfo=datetime.timezone.utc)),
        ),
    ]
