# Generated by Django 5.2.4 on 2025-07-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_alter_produit_seuil_stock_bas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='seuil_stock_bas',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Niveau pour déclencher une alerte', null=True),
        ),
    ]
