# Generated by Django 5.2.4 on 2025-07-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_categorie_options_alter_lignedevente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='seuil_stock_bas',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Niveau pour déclencher une alerte', null=True),
        ),
    ]
