# Generated by Django 5.2.4 on 2025-07-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_alter_produit_seuil_stock_bas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='seuil_stock_bas',
            field=models.PositiveIntegerField(default=2, help_text='Niveau pour déclencher une alerte'),
        ),
    ]
