# Generated by Django 5.2.4 on 2025-09-04 12:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_alter_produit_seuil_stock_bas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='client_nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_encaisse',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('PAYEE', 'Payée'), ('PARTIELLE', 'Partiellement payée'), ('IMPAYEE', 'Impayée')], default='IMPAYEE', max_length=12),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE', 'Mobile Money'), ('BANQUE', 'Virement / Carte'), ('AUTRE', 'Autre')], default='ESPECES', max_length=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='boutique.vente')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
