# Generated by Django 5.2.4 on 2025-09-04 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_vente_client_nom_vente_montant_encaisse_vente_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 4, 8, 3, 46, 679687, tzinfo=datetime.timezone.utc)),
        ),
    ]
