# Generated by Django 5.2.4 on 2025-09-04 08:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_alter_vente_date_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 4, 8, 22, 52, 774433, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='boutique.vente'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='date_mouvement',
            field=models.DateField(default=datetime.date(2025, 9, 4)),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 4, 8, 22, 34, 255029, tzinfo=datetime.timezone.utc)),
        ),
    ]
