# Generated by Django 5.2.4 on 2025-09-04 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_mouvementstock_created_at_mouvementstock_vente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 4, 8, 54, 35, 756673, tzinfo=datetime.timezone.utc)),
        ),
    ]
