# Generated by Django 5.2.4 on 2025-09-04 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_alter_vente_date_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 4, 9, 9, 45, 752052, tzinfo=datetime.timezone.utc)),
        ),
    ]
