# Generated by Django 5.2.4 on 2025-09-05 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_alter_vente_date_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='date_mouvement',
            field=models.DateField(default=datetime.date(2025, 9, 5)),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 8, 57, 49, 268592, tzinfo=datetime.timezone.utc)),
        ),
    ]
